version: "3.8"
services: 
    progra-web-backend:
        image: progra-web-backend
        ports:
            - "9000:9000"
        depends_on: 
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"